// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calc-block__button': string;
  'calc-block__button_number': string;
}
export const cssExports: CssExports;
export default cssExports;
