const ADD_RESULT = 'ADD_RESULT';
const RESET_RESULT = 'RESET_RESULT';
const ADD_OPERATION = 'ADD_OPERATION';
const RESET_OPERATION = 'RESET_OPERATION';
const ADD_VALUE = 'ADD_VALUE';
const RESET_VALUE = 'RESET_VALUE';
const ADD_OPTION = 'ADD_OPTION';
const RESET_OPTION = 'RESET_OPTION';

export {
    ADD_RESULT,
    RESET_RESULT,
    ADD_OPERATION,
    RESET_OPERATION,
    ADD_VALUE,
    RESET_VALUE,
    ADD_OPTION,
    RESET_OPTION
}
