// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calc-block': string;
  'calc-block__button': string;
  'calc-block__numbers': string;
  'calc-block__operations': string;
  'calc-block__options': string;
  'calc-block__wrap': string;
  'container': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
